version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    restart: always
    image: julianspiess/syersy-web
    volumes:
      - ./app:/app
    ports: 
      - "3000:3000"